package catalog

import (
	"encoding/binary"
	"encoding/json"
	"strconv"
	"strings"

	"github.com/vyrodovalexey/mcp-mock-server/internal/determinism"
	"github.com/vyrodovalexey/mcp-mock-server/scenario"
)

// generator computes generated items for one kind on demand. It is a pure
// function of the instance key, the kind and the index: nothing is stored, so
// building a generator is O(1) regardless of count (ADR-004). It holds the
// derivation base key (instanceKey.Derive(DomainCatalogue, kind)) precomputed
// once so per-item generation is a single further Derive.
type generator struct {
	base            determinism.Key
	kind            Kind
	count           int
	prefix          string // name prefix from the template, before the index
	suffix          string // name suffix from the template, after the index
	pad             int    // zero-pad width for the index (0 = no padding)
	descriptionSize int    // words in a generated description
	scopes          []string
	clientCaps      []string
}

// Default generation parameters. The default template mirrors ADR-004's
// "tool_{{i:05d}}" for every kind, differing only in the kind-specific prefix so
// names never collide across kinds. Changing any of these changes generated
// names and is a breaking change (see testdata/names.golden).
const (
	defaultPad             = 5
	defaultDescriptionSize = 8
)

// defaultPrefix returns the default name prefix for a kind, e.g. "tool_" so the
// default name for tool 42 is "tool_00042".
func defaultPrefix(kind Kind) string {
	switch kind {
	case KindTool:
		return "tool_"
	case KindPrompt:
		return "prompt_"
	case KindResource:
		return "resource_"
	case KindResourceTemplate:
		return "resourceTemplate_"
	default:
		return string(kind) + "_"
	}
}

// generatedSpec is the resolved, non-pointer generation parameters for a kind.
// It is produced from a *scenario.Generated by applying defaults for absent
// (nil) fields, honouring the pointer/absent-vs-zero idiom: a non-nil pointer to
// 0 count means "generate none", distinct from an absent block.
type generatedSpec struct {
	count           int
	template        string
	descriptionSize int
	scopes          []string
	clientCaps      []string
}

// resolveGenerated turns the scenario's optional generation block into a
// concrete spec, applying defaults. A nil block means the kind is not generated
// (count 0).
func resolveGenerated(kind Kind, g *scenario.Generated) generatedSpec {
	spec := generatedSpec{
		count:           0,
		template:        defaultPrefix(kind) + "{{i:05d}}",
		descriptionSize: defaultDescriptionSize,
	}
	if g == nil {
		return spec
	}
	if g.Count != nil {
		spec.count = *g.Count
	}
	if g.NameTemplate != nil {
		spec.template = *g.NameTemplate
	}
	if g.DescriptionWords != nil {
		spec.descriptionSize = *g.DescriptionWords
	}
	spec.scopes = g.RequiredScopes
	spec.clientCaps = g.RequiredClientCapabilities
	return spec
}

// newGenerator builds a generator for a kind from an instance key and a resolved
// spec. It precomputes the per-kind derivation base and parses the name template
// once so per-item work is minimal.
func newGenerator(instanceKey determinism.Key, kind Kind, spec generatedSpec) *generator {
	prefix, suffix, pad := parseTemplate(spec.template)
	return &generator{
		// The kind string is a fixed, short byte part; DomainCatalogue framing
		// (domain || 0x00 || parts) keeps one kind's names independent of
		// another's without a length prefix, because the kind values are a fixed
		// set with no prefix relationship.
		base:            instanceKey.Derive(determinism.DomainCatalogue, []byte(string(kind))),
		kind:            kind,
		count:           spec.count,
		prefix:          prefix,
		suffix:          suffix,
		pad:             pad,
		descriptionSize: spec.descriptionSize,
		scopes:          spec.scopes,
		clientCaps:      spec.clientCaps,
	}
}

// name returns the deterministic name of generated item i. It is a pure function
// of the template and i and does not touch the seed, so name inversion
// ([nameIndex]) is exact.
func (g *generator) name(i int) string {
	var b strings.Builder
	b.Grow(len(g.prefix) + g.pad + len(g.suffix))
	b.WriteString(g.prefix)
	if g.pad > 0 {
		s := strconv.Itoa(i)
		for p := len(s); p < g.pad; p++ {
			b.WriteByte('0')
		}
		b.WriteString(s)
	} else {
		b.WriteString(strconv.Itoa(i))
	}
	b.WriteString(g.suffix)
	return b.String()
}

// nameIndex inverts [name]: it returns the index a generated name encodes and
// whether the name is a well-formed generated name for this generator. It never
// scans; it strips the prefix/suffix and parses the middle as a non-negative
// integer, rejecting names whose padding, sign or range does not round-trip.
func (g *generator) nameIndex(name string) (int, bool) {
	mid, ok := strings.CutPrefix(name, g.prefix)
	if !ok {
		return 0, false
	}
	mid, ok = strings.CutSuffix(mid, g.suffix)
	if !ok {
		return 0, false
	}
	if mid == "" {
		return 0, false
	}
	// Reject a leading sign or non-digit so only canonical encodings invert.
	for i := 0; i < len(mid); i++ {
		if mid[i] < '0' || mid[i] > '9' {
			return 0, false
		}
	}
	idx, err := strconv.Atoi(mid)
	if err != nil || idx < 0 || idx >= g.count {
		return 0, false
	}
	// Enforce round-trip: the canonical rendering of idx must equal the input,
	// so an over-padded or under-padded variant does not alias a valid index.
	if g.name(idx) != name {
		return 0, false
	}
	return idx, true
}

// generate computes item i. It derives a per-item key and draws a small,
// fixed-shape description and input schema from it, so item content is
// deterministic and independent of access order (ADR-002 rule 2). The index is
// encoded big-endian so the derivation is host-byte-order independent.
func (g *generator) generate(i int) Item {
	var idxBE [8]byte
	binary.BigEndian.PutUint64(idxBE[:], uint64(i)) //nolint:gosec // i is a validated non-negative index < count
	itemKey := g.base.Derive(determinism.DomainCatalogue, idxBE[:])

	return Item{
		Name:                       g.name(i),
		Kind:                       g.kind,
		Authored:                   false,
		Description:                g.description(itemKey),
		InputSchema:                g.inputSchema(),
		RequiredScopes:             g.scopes,
		RequiredClientCapabilities: g.clientCaps,
	}
}

// description builds a deterministic description of descriptionSize words drawn
// from a fixed word list by the item's RNG. An empty word list or a
// non-positive size yields "".
func (g *generator) description(itemKey determinism.Key) string {
	if g.descriptionSize <= 0 {
		return ""
	}
	rng := itemKey.RNG()
	var b strings.Builder
	for w := 0; w < g.descriptionSize; w++ {
		if w > 0 {
			b.WriteByte(' ')
		}
		b.WriteString(descriptionWords[rng.IntN(len(descriptionWords))])
	}
	return b.String()
}

// inputSchema returns a small, fixed generated JSON Schema shape. It is the same
// for every generated item of a kind in Phase 1 (schema-shape variation is a
// later phase), and is emitted verbatim like an authored schema.
func (g *generator) inputSchema() json.RawMessage {
	return generatedInputSchema
}

// generatedInputSchema is the fixed Phase 1 generated input schema. It is a
// package-level immutable value shared by every generated item — never mutated,
// so sharing the backing array across items and across instances is safe and
// keeps generation allocation-free for this field.
var generatedInputSchema = json.RawMessage(`{"type":"object","properties":{"input":{"type":"string"}},"additionalProperties":false}`)

// descriptionWords is the fixed vocabulary generated descriptions draw from. It
// is immutable and shared; the RNG selects indices into it deterministically.
var descriptionWords = []string{
	"deterministic", "virtual", "catalog", "primitive", "generated",
	"overlay", "instance", "snapshot", "reproducible", "mock",
}

// parseTemplate splits a name template of the form "<prefix>{{i:0Nd}}<suffix>"
// or "<prefix>{{i}}<suffix>" into its prefix, suffix and zero-pad width. A
// template with no "{{i…}}" placeholder is treated as an all-prefix template
// with no index, which yields non-unique names — a misconfiguration the schema
// prevents, handled here without panicking by using pad 0 and an empty middle.
func parseTemplate(tmpl string) (prefix, suffix string, pad int) {
	const open = "{{i"
	const close = "}}"
	start := strings.Index(tmpl, open)
	if start < 0 {
		return tmpl, "", 0
	}
	rest := tmpl[start+len(open):]
	end := strings.Index(rest, close)
	if end < 0 {
		return tmpl, "", 0
	}
	spec := rest[:end] // "" or ":05d" or ":d"
	prefix = tmpl[:start]
	suffix = rest[end+len(close):]
	pad = parsePad(spec)
	return prefix, suffix, pad
}

// parsePad reads the zero-pad width from a placeholder spec such as ":05d". It
// returns 0 for ":d", "" or any spec it does not understand, so an unfamiliar
// format degrades to an unpadded index rather than an error.
func parsePad(spec string) int {
	spec, ok := strings.CutPrefix(spec, ":")
	if !ok {
		return 0
	}
	spec = strings.TrimSuffix(spec, "d")
	spec, ok = strings.CutPrefix(spec, "0")
	if !ok {
		return 0
	}
	n, err := strconv.Atoi(spec)
	if err != nil || n < 0 {
		return 0
	}
	return n
}
